### PR TITLE
Add channel mention highlighting

### PR DESCRIPTION
**Pull request by Aareon**

### CODE REVIEW

**Comment by Aareon** [comment]
Need to move the separate flags and create a Boolean in the servers key in `self.channel_list` to mark whether you’ve been mentioned or new messages have been sent.

**Comment by AnonymousDapper** [comment]
I'd rather have both the mention and new_messages flag be in the channel_list dict. Because of that, and the fact that I'm gonna try to add sound alerts, I'll not merge this. Thanks tho

**Comment by Aareon** [comment]
I will be moving both of these flags into the channels dict asap.

**Comment by Aareon** [comment]
Understood. Good luck! Closing.

**Pull request closed without merging**
